language: hun
output_dir: output
data_dir: ../2022SegmentationST/data
model_suffix: -by_char
model_ext: pt
predictions_ext: tsv

preprocessing:
  min_freq: 2
  batch_size: 128
  shuffle: False
  initial_weights: 0.8

encoder_decoder:
  bidirectional: True
  embedding_dim: 64
  hidden_dim: 512
  n_layers: 2
  dropout: 0.3

training:
  enabled: True
  learning_rate: 0.05 # This is the initial learning rate
  learning_rate_min: 0.0001
  learning_rate_factor: 0.1
  patience: 1 # How many epochs without loss improvement until training is stopped (only after learning rate at min)
  epochs: 12 # training should be stopped by early stopping before this number
  teacher_forcing_ratio: 0.5
  clip: 1.0

predictions:
  max_output: 65 # length of longest morpheme string + 2

special_tokens:
  sos_token: <SOS>
  eos_token: <EOS>
  pad_token: <PAD>
  unknown_token: <UNK>
