language: hun
output_dir: output
data_dir: ../2022SegmentationST/data
model_suffix: -by_char
model_ext: pt
predictions_ext: tsv

preprocessing:
  min_freq: 2
  batch_size: 128
  shuffle: False
  initial_weights: 0.8

encoder_decoder:
  embedding_dim: 64
  hidden_dim: 1024
  n_layers: 2
  dropout: 0.2

training:
  enabled: True
  learning_rate: 0.01
  epochs: 25 # training should be stopped by early stopping before this number
  teacher_forcing_ratio: 0.5
  clip: 1.0
  early_stopping: 3

predictions:
  max_output: 65 # length of longest morpheme string + 2

special_tokens:
  sos_token: <SOS>
  eos_token: <EOS>
  pad_token: <PAD>
  unknown_token: <UNK>
