language: hun
model_dir: model
data_dir: ../2022SegmentationST/data
model_suffix: -by_char
model_ext: pt
predictions_ext: tsv

preprocessing:
  min_freq: 2
  batch_size: 128
  shuffle: False
  initial_weights: 0.8

encoder_decoder:
  embedding_dim: 256
  hidden_dim: 512
  n_layers: 2
  dropout: 0.5

training:
  enabled: False
  learning_rate: 0.001
  epochs: 10
  teacher_forcing_ratio: 0.5
  clip: 1.0

predictions:
  max_output: 65 # length of longest morpheme string + 2

special_tokens:
  sos_token: <SOS>
  eos_token: <EOS>
  pad_token: <PAD>
  unknown_token: <UNK>
